---
# Activate a number of Apache modules.

- name: Install package apache2
  action: apt pkg=apache2 state=present

- name: Enable Apache ssl module
  apache2_module:
    state: present
    name: ssl
  notify:
   - restart apache

- name: Ensure apache is running
  action: service name=apache2 state=started
